#!/bin/bash

set -e

source setup-helpers

config="${XDG_CONFIG_DIR:-$HOME/.config}"

# TODO: Make this cross-platform
sudo add-apt-repository ppa:neovim-ppa/unstable
sudo apt-get update
sudo apt install neovim

mkdir -p "$config"

rm "$config/nvim" >/dev/null 2>&1 || true
ln -s "$dotfiles_dir/nvim" "$config/nvim"
