#!/bin/bash

set -e

scriptdir="$(dirname $0)"
cd "$scriptdir"

source setup-helpers

setup_nvim() {
  local from="$dotfiles_dir/nvim"
  local to="$(wslpath $(wslvar LOCALAPPDATA))/nvim"

  rm -rf "$to"
  cp -r "$from" "$to"
}

setup_nvim

